name: carburetor
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  meta: ^1.17.0

dev_dependencies:
  lints: ^5.0.0
