name: carburetor
description: Dependency injection library for Dart with code generation.
version: 0.0.2
repository: https://github.com/DIG-/dart-carburetor
topics:
  - dependency-injection
  - code-generation
  - build
  - source-gen

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  meta: ^1.17.0

dev_dependencies:
  lints: ^5.0.0
