# More info: https://pub.dev/packages/build_config
builders:
  carburetor_info_extractor:
    import: "package:carburetor_build/carburetor_build.dart"
    builder_factories: ["carburetorInfoExtractor"]
    build_extensions: { ".dart": [".carburetor-info.json"] }
    applies_builders: ["carburetor_module_creator"]
    auto_apply: dependents
    build_to: cache
  carburetor_module_creator:
    import: "package:carburetor_build/carburetor_build.dart"
    builder_factories: ["carburetorModuleCreator"]
    build_extensions: { ".dart": [".carburetor.dart"] }
    runs_before: ["carburetor_info_extractor"]
    required_inputs: [".carburetor-info.json"]
    auto_apply: dependents
    build_to: source
